
[package]
authors = ["Viacheslav Azarov <public@religiosa.ru>"]
edition = "2021"
name    = "language_detection"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
lingua      = "1.7.2"
napi        = { version = "3.0.0", features = ["async"] }
napi-derive = "3.0.0"
tokio       = { version = "1", features = ["macros", "rt"] }

[build-dependencies]
napi-build = "2"

[profile.release]
lto   = true
strip = "symbols"
