/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Low accuracy detection of all available languages. This will detect any
 * supported language, besides explicitly filtered out because of higher amount
 * of false positives.
 */
export declare function detectAllLanguagesFast(input: string): Array<NapiDetectedLanguage>

/**
 * High accuracy detections, but only detects Russian or English.
 * This is intended to find direct language policy violation (using English on
 * a Russian day or vice versa), but won't detect usage of any other language
 * outside of those two.
 * Confidence isn't calculated here, because it's meaningless.
 */
export declare function isRussianOrEnglish(input: string): Array<NapiDetectedLanguage>

export declare function loadLanguageModels(): void

export interface NapiDetectedLanguage {
  startIndex: number
  endIndex: number
  wordCount: number
  language: string
}
