/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Low accuracy detection of all available languages. This will detect any
 * supported language, besides explicitly filtered out because of higher amount
 * of false positives.
 */
export declare function detectAllLanguagesFast(input: string): Promise<Array<NapiDetectedLanguage>>

/**
 * High accuracy detections, but only detects Russian or English.
 * This is intended to find direct language policy violation (using English on
 * a Russian day or vice versa), but won't detect usage of any other language
 * outside of those two.
 * Confidence isn't calculated here, because it's meaningless.
 */
export declare function isRussianOrEnglish(input: string): Promise<Array<NapiDetectedLanguage>>

/**
 * Preload language models.
 *
 * Without a call to this method language models will be lazily initialized,
 * Dramatically increasing first detection call latency.
 */
export declare function loadLanguageModels(): void

/** Language detection result */
export interface NapiDetectedLanguage {
  /** Start index in bytes */
  startIndex: number
  /** End index in bytes */
  endIndex: number
  /** Count of words in this language */
  wordCount: number
  /** ISO 639-1 language code, e.g. "en", "ru" */
  language: string
}
